### ISSUE TITLE
running monte with pypy gives ImportError about `terml

### ISSUE THREAD

**Issue by dckc** [monte-language/monte#17]
For fun, I tried to run `hello.mt` with pypy; no joy:

```python
(mpp)~/src/monte$ bin/monte monte/src/examples/hello.mt
Traceback (most recent call last):
  File "app_main.py", line 72, in run_toplevel
  File "bin/monte", line 11, in <module>
    import monte.runtime.load
  File "/usr/local/src/monte/monte/runtime/load.py", line 4, in <module>
    from monte.compiler import ecompile
  File "/usr/local/src/monte/monte/compiler.py", line 5, in <module>
    from monte import ast
  File "/usr/local/src/monte/monte/ast.py", line 5, in <module>
    from terml.nodes import Tag, Term
ImportError: No module named terml
(mpp)connolly@pav:~/src/monte$ 
```

Steps that led up to the above error:

```
$ sudo apt-get install pypy
$ virtualenv -p /usr/bin/pypy ~/pyenv/mp
$ . ~/pyenv/mpp/bin/activate
(mpp)~/src/monte$ python --version
Python 2.7.3 (2.2.1+dfsg-1, Nov 28 2013, 05:13:10)
[PyPy 2.2.1 with GCC 4.8.2]
```

**Comment by edunham** [comment]
Reproduced: 

```
$ virtualenv -p /usr/bin/pypy pypy_venv
$ source pypy_venv/bin/activate
$ python --version
Python 2.7.8 (10f1b29a2bd2, Feb 05 2015, 16:50:17)
[PyPy 2.5.0 with GCC 4.9.2 20141224 (prerelease)]
$ bin/monte monte/src/examples/hello.mt 
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "bin/monte", line 10, in <module>
    from monte.runtime.load import eval as monte_eval, monteImport
  File "/home/miea/repos/monte/monte/monte/runtime/load.py", line 4, in <module>
    from monte.compiler import ecompile
  File "/home/miea/repos/monte/monte/monte/compiler.py", line 5, in <module>
    from monte import ast
  File "/home/miea/repos/monte/monte/monte/ast.py", line 5, in <module>
    from terml.nodes import Tag, Term
ImportError: No module named terml
```

**Comment by edunham** [comment]
With the normal venv activated, 
```
>>> import terml
>>> terml
<module 'terml' from '/home/miea/repos/monte/monte/v/lib/python2.7/site-packages/terml/__init__.pyc'>
>>> 
```
So, terml showed up in site-packages for the normal venv but not the pypy one. 
This made me realize the fix was embarrassingly obvious: we both neglected to 
```
pip install -r requirements.txt
```
before trying to run Monte code. No wonder it didn't work. 

After installing the requirements, I ceased being able to reproduce the error.
